{
   "pairs":{
      "kucoin":{
         "BTC-ETH":{
            "enabled":true,
            "strategy":"gain",
            "override":{

            }
         }
      }
   },
   "strategies":{
      "gain":{
         "BUY_LEVEL":1,
         "GAIN":0.1,
		 
         "BUY_METHOD":"gain",
         "BUY_ENABLED":true,
         "SELL_METHOD":"gain",
         "SELL_ENABLED":true,
         "TRADING_LIMIT":0.002,
	 "TL_PERC": 0,
 	 "TL_ALLIN": false,
         "KEEP_QUOTE": 0,
	 "MIN_VOLUME_TO_BUY":0.001,
         "MIN_VOLUME_TO_SELL":0.001,
         "IGNORE_TRADES_BEFORE":0,
         "TRADING_FEES":0.25,
         "FUNDS_RESERVE":0.0001,
		 
         "HIGH_BB":45,
         "LOW_BB":45,
         "CANDLES_LENGTH":99,
         "PERIOD":15,
         "EMA_LENGTH":50,
         "EMA1":16,
         "EMA2":8,
         "STDV":2,
         "SMAPERIOD":50,
         "SLOW_SMA":2,
         "FAST_SMA":1,
         "MACD_SHORT":12,
         "MACD_LONG":26,
         "MACD_SIGNAL":9,
         "STOCH_ENABLED":false,
         "STOCH_METHOD":"oscillator",
         "STOCH_BUY_LEVEL":20,
         "STOCH_SELL_LEVEL":80,
         "STOCH_K":14,
         "SLOW_STOCH_K":3,
         "STOCH_D":3,
         "DI_PERIOD":14,
         "EMASPREAD":false,
         "EMAx":0.5,
         "ADX_LEVEL":25,
         "ADX_ENABLED":false,
         "RSI_BUY_ENABLED":false,
         "RSI_SELL_ENABLED":false,
         "RSI_METHOD":"oscillator",
         "RSI_BUY_LEVEL":30,
         "RSI_SELL_LEVEL":70,
         "RSI_LENGTH":14,
         "MFI_ENABLED":false,
         "MFI_LENGTH":14,
         "MFI_SELL_LEVEL":30,
         "MFI_BUY_LEVEL":70,
         "KUMO_SENTIMENTS":true,
         "ATRX":3,
         "ATR_PERIOD":14,
         "BTC_PND_PROTECTION":false,
         "BTC_MONEY_FLOW":35,
		 
         "DOUBLE_UP":false,
         "DOUBLE_UP_CAP":1,
         "DU_CAP_COUNT":0,
         "DU_METHOD":"HIGHBB",
         "DU_BUYDOWN":2,
         "RSI_DU_BUY":30,
		 
         "RT_ENABLED":true,
         "RT_MAXBAG_PROTECTION":10,
         "RT_SELL_UP":0.1,
         "RT_TREND_ENABLED":true,
         "RT_BUY_LEVEL":0.8,
         "RT_BUYLVL1":0.6,
         "RT_BUYLVL2":2,
         "RT_BUYLVL3":70,
         "RT_BUYLVL":1,
         "RT_GAIN":0.1,
         "RT_SELLLVL1":0.6,
         "RT_SELLLVL2":2,
         "RT_SELLLVL3":70,
         "RT_SELLLVL":1,
		 
         "TRAIL_ME_BUY":false,
         "TRAIL_ME_SELL":false,
         "TRAIL_ME_DU":false,
         "TM_RT_SELL":false,
         "TRAIL_ME_RT":false,
         "TRAIL_ME_SELL_RANGE":0.5,
         "TRAIL_ME_BUY_RANGE":0.5,
         "TRAIL_ME_RT_SELL_RANGE":0.5,
		 
         "PANIC_SELL":false,
         "STOP_LIMIT":60,
         "TRADES_TIMEOUT":0,
		 
         "BUYLVL1":0.6,
         "BUYLVL2":2,
         "BUYLVL3":70,
         "BUYLVL":1,
         "SELLLVL1":0.6,
         "SELLLVL2":2,
         "SELLLVL3":70,
         "SELLLVL":1,
		 
         "BUY_RANGE":0.1,
         "SELL_RANGE":0.1,
         "TSSL_TARGET_ONLY":true,
		 
		 "TAKE_PROFIT": false,
		 "TP_RANGE": 0.5,
		 
         "PP_BUY":0,
         "PP_SELL":99999
      },
      "bb":{
         "BUY_LEVEL":0.1,
         "GAIN":0.1,
         "HIGH_BB":45,
         "LOW_BB":45,
		 
         "BUY_METHOD":"bb",
         "BUY_ENABLED":true,
         "SELL_METHOD":"bb",
         "SELL_ENABLED":true,
         "TRADING_LIMIT":0.002,
	 "TL_PERC": 0,
 	 "TL_ALLIN": false,
         "KEEP_QUOTE": 0,
         "MIN_VOLUME_TO_BUY":0.001,
         "MIN_VOLUME_TO_SELL":0.001,
         "IGNORE_TRADES_BEFORE":0,
         "TRADING_FEES":0.25,
         "FUNDS_RESERVE":0.0001,
		 
         "CANDLES_LENGTH":99,
         "PERIOD":15,
         "EMA_LENGTH":50,
         "EMA1":16,
         "EMA2":8,
         "STDV":2,
         "SMAPERIOD":50,
         "SLOW_SMA":2,
         "FAST_SMA":1,
         "MACD_SHORT":12,
         "MACD_LONG":26,
         "MACD_SIGNAL":9,
         "STOCH_ENABLED":false,
         "STOCH_METHOD":"oscillator",
         "STOCH_BUY_LEVEL":20,
         "STOCH_SELL_LEVEL":80,
         "STOCH_K":14,
         "SLOW_STOCH_K":3,
         "STOCH_D":3,
         "DI_PERIOD":14,
         "EMASPREAD":false,
         "EMAx":0.5,
         "ADX_LEVEL":25,
         "ADX_ENABLED":false,
         "RSI_BUY_ENABLED":false,
         "RSI_SELL_ENABLED":false,
         "RSI_METHOD":"oscillator",
         "RSI_BUY_LEVEL":30,
         "RSI_SELL_LEVEL":70,
         "RSI_LENGTH":14,
         "MFI_ENABLED":false,
         "MFI_LENGTH":14,
         "MFI_SELL_LEVEL":30,
         "MFI_BUY_LEVEL":70,
         "KUMO_SENTIMENTS":true,
         "ATRX":3,
         "ATR_PERIOD":14,
         "BTC_PND_PROTECTION":false,
         "BTC_MONEY_FLOW":35,
		 
         "DOUBLE_UP":false,
         "DOUBLE_UP_CAP":1,
         "DU_CAP_COUNT":0,
         "DU_METHOD":"HIGHBB",
         "DU_BUYDOWN":2,
         "RSI_DU_BUY":30,
		 
         "RT_ENABLED":true,
         "RT_MAXBAG_PROTECTION":10,
         "RT_SELL_UP":0.1,
         "RT_TREND_ENABLED":true,
         "RT_BUY_LEVEL":0.8,
         "RT_BUYLVL1":0.6,
         "RT_BUYLVL2":2,
         "RT_BUYLVL3":70,
         "RT_BUYLVL":1,
         "RT_GAIN":0.1,
         "RT_SELLLVL1":0.6,
         "RT_SELLLVL2":2,
         "RT_SELLLVL3":70,
         "RT_SELLLVL":1,
		 
         "TRAIL_ME_BUY":false,
         "TRAIL_ME_SELL":false,
         "TRAIL_ME_DU":false,
         "TM_RT_SELL":false,
         "TRAIL_ME_RT":false,
         "TRAIL_ME_SELL_RANGE":0.5,
         "TRAIL_ME_BUY_RANGE":0.5,
         "TRAIL_ME_RT_SELL_RANGE":0.5,
		 
         "PANIC_SELL":false,
         "STOP_LIMIT":60,
         "TRADES_TIMEOUT":0,
		 
         "BUYLVL1":0.6,
         "BUYLVL2":2,
         "BUYLVL3":70,
         "BUYLVL":1,
         "SELLLVL1":0.6,
         "SELLLVL2":2,
         "SELLLVL3":70,
         "SELLLVL":1,
		 
         "BUY_RANGE":0.1,
         "SELL_RANGE":0.1,
         "TSSL_TARGET_ONLY":true,
		 
		 "TAKE_PROFIT": false,
		 "TP_RANGE": 0.5,
		 
         "PP_BUY":0,
         "PP_SELL":99999
      },
      "stepgain":{
         "BUY_LEVEL":0.1,
         "BUYLVL1":0.6,
         "BUYLVL2":2,
         "BUYLVL3":70,
         "BUYLVL":1,
         "GAIN":0.1,
         "SELLLVL1":0.6,
         "SELLLVL2":2,
         "SELLLVL3":70,
         "SELLLVL":1,
		 
         "BUY_METHOD":"stepgain",
         "BUY_ENABLED":true,
         "SELL_METHOD":"stepgain",
         "SELL_ENABLED":true,
         "TRADING_LIMIT":0.002,
	 "TL_PERC": 0,
 	 "TL_ALLIN": false,
         "KEEP_QUOTE": 0,
         "MIN_VOLUME_TO_BUY":0.001,
         "MIN_VOLUME_TO_SELL":0.001,
         "IGNORE_TRADES_BEFORE":0,
         "TRADING_FEES":0.25,
         "FUNDS_RESERVE":0.0001,
		 
         "HIGH_BB":45,
         "LOW_BB":45,
         "CANDLES_LENGTH":99,
         "PERIOD":15,
         "EMA_LENGTH":50,
         "EMA1":16,
         "EMA2":8,
         "STDV":2,
         "SMAPERIOD":50,
         "SLOW_SMA":2,
         "FAST_SMA":1,
         "MACD_SHORT":12,
         "MACD_LONG":26,
         "MACD_SIGNAL":9,
         "STOCH_ENABLED":false,
         "STOCH_METHOD":"oscillator",
         "STOCH_BUY_LEVEL":20,
         "STOCH_SELL_LEVEL":80,
         "STOCH_K":14,
         "SLOW_STOCH_K":3,
         "STOCH_D":3,
         "DI_PERIOD":14,
         "EMASPREAD":false,
         "EMAx":0.5,
         "ADX_LEVEL":25,
         "ADX_ENABLED":false,
         "RSI_BUY_ENABLED":false,
         "RSI_SELL_ENABLED":false,
         "RSI_METHOD":"oscillator",
         "RSI_BUY_LEVEL":30,
         "RSI_SELL_LEVEL":70,
         "RSI_LENGTH":14,
         "MFI_ENABLED":false,
         "MFI_LENGTH":14,
         "MFI_SELL_LEVEL":30,
         "MFI_BUY_LEVEL":70,
         "KUMO_SENTIMENTS":true,
         "ATRX":3,
         "ATR_PERIOD":14,
         "BTC_PND_PROTECTION":false,
         "BTC_MONEY_FLOW":35,
		 
         "DOUBLE_UP":false,
         "DOUBLE_UP_CAP":1,
         "DU_CAP_COUNT":0,
         "DU_METHOD":"HIGHBB",
         "DU_BUYDOWN":2,
         "RSI_DU_BUY":30,
		 
         "RT_ENABLED":true,
         "RT_MAXBAG_PROTECTION":10,
         "RT_SELL_UP":0.1,
         "RT_TREND_ENABLED":true,
         "RT_BUY_LEVEL":0.8,
         "RT_BUYLVL1":0.6,
         "RT_BUYLVL2":2,
         "RT_BUYLVL3":70,
         "RT_BUYLVL":1,
         "RT_GAIN":0.1,
         "RT_SELLLVL1":0.6,
         "RT_SELLLVL2":2,
         "RT_SELLLVL3":70,
         "RT_SELLLVL":1,
		 
         "TRAIL_ME_BUY":false,
         "TRAIL_ME_SELL":false,
         "TRAIL_ME_DU":false,
         "TM_RT_SELL":false,
         "TRAIL_ME_RT":false,
         "TRAIL_ME_SELL_RANGE":0.5,
         "TRAIL_ME_BUY_RANGE":0.5,
         "TRAIL_ME_RT_SELL_RANGE":0.5,
		 
         "PANIC_SELL":false,
         "STOP_LIMIT":60,
         "TRADES_TIMEOUT":0,
		 
         "BUY_RANGE":0.1,
         "SELL_RANGE":0.1,
         "TSSL_TARGET_ONLY":true,
		 
		 "TAKE_PROFIT": false,
		 "TP_RANGE": 0.5,
		 
         "PP_BUY":0,
         "PP_SELL":99999
      },
      "tssl":{
         "BUY_LEVEL":0.1,
         "BUY_RANGE":0.1,
         "GAIN":0.1,
         "SELL_RANGE":0.1,
         "TSSL_TARGET_ONLY":true,
		 
         "BUY_METHOD":"tssl",
         "BUY_ENABLED":true,
         "SELL_METHOD":"tssl",
         "SELL_ENABLED":true,
         "TRADING_LIMIT":0.002,
	 "TL_PERC": 0,
 	 "TL_ALLIN": false,
         "KEEP_QUOTE": 0,
         "MIN_VOLUME_TO_BUY":0.001,
         "MIN_VOLUME_TO_SELL":0.001,
         "IGNORE_TRADES_BEFORE":0,
         "TRADING_FEES":0.25,
         "FUNDS_RESERVE":0.0001,
		 
         "HIGH_BB":45,
         "LOW_BB":45,
         "CANDLES_LENGTH":99,
         "PERIOD":15,
         "EMA_LENGTH":50,
         "EMA1":16,
         "EMA2":8,
         "STDV":2,
         "SMAPERIOD":50,
         "SLOW_SMA":2,
         "FAST_SMA":1,
         "MACD_SHORT":12,
         "MACD_LONG":26,
         "MACD_SIGNAL":9,
         "STOCH_ENABLED":false,
         "STOCH_METHOD":"oscillator",
         "STOCH_BUY_LEVEL":20,
         "STOCH_SELL_LEVEL":80,
         "STOCH_K":14,
         "SLOW_STOCH_K":3,
         "STOCH_D":3,
         "DI_PERIOD":14,
         "EMASPREAD":false,
         "EMAx":0.5,
         "ADX_LEVEL":25,
         "ADX_ENABLED":false,
         "RSI_BUY_ENABLED":false,
         "RSI_SELL_ENABLED":false,
         "RSI_METHOD":"oscillator",
         "RSI_BUY_LEVEL":30,
         "RSI_SELL_LEVEL":70,
         "RSI_LENGTH":14,
         "MFI_ENABLED":false,
         "MFI_LENGTH":14,
         "MFI_SELL_LEVEL":30,
         "MFI_BUY_LEVEL":70,
         "KUMO_SENTIMENTS":true,
         "ATRX":3,
         "ATR_PERIOD":14,
         "BTC_PND_PROTECTION":false,
         "BTC_MONEY_FLOW":35,
		 
         "DOUBLE_UP":false,
         "DOUBLE_UP_CAP":1,
         "DU_CAP_COUNT":0,
         "DU_METHOD":"HIGHBB",
         "DU_BUYDOWN":2,
         "RSI_DU_BUY":30,
		 
         "RT_ENABLED":true,
         "RT_MAXBAG_PROTECTION":10,
         "RT_SELL_UP":0.1,
         "RT_TREND_ENABLED":true,
         "RT_BUY_LEVEL":0.8,
         "RT_BUYLVL1":0.6,
         "RT_BUYLVL2":2,
         "RT_BUYLVL3":70,
         "RT_BUYLVL":1,
         "RT_GAIN":0.1,
         "RT_SELLLVL1":0.6,
         "RT_SELLLVL2":2,
         "RT_SELLLVL3":70,
         "RT_SELLLVL":1,
		 
         "TRAIL_ME_BUY":false,
         "TRAIL_ME_SELL":false,
         "TRAIL_ME_DU":false,
         "TM_RT_SELL":false,
         "TRAIL_ME_RT":false,
         "TRAIL_ME_SELL_RANGE":0.5,
         "TRAIL_ME_BUY_RANGE":0.5,
         "TRAIL_ME_RT_SELL_RANGE":0.5,
		 
         "PANIC_SELL":false,
         "STOP_LIMIT":60,
         "TRADES_TIMEOUT":0,
		 
         "BUYLVL1":0.6,
         "BUYLVL2":2,
         "BUYLVL3":70,
         "BUYLVL":1,
         "SELLLVL1":0.6,
         "SELLLVL2":2,
         "SELLLVL3":70,
         "SELLLVL":1,
		 
		 "TAKE_PROFIT": false,
		 "TP_RANGE": 0.5,
		 
         "PP_BUY":0,
         "PP_SELL":99999
      },
      "pp":{
         "PP_BUY":0,
         "PP_SELL":99999,
		 
         "BUY_METHOD":"pp",
         "BUY_ENABLED":true,
         "SELL_METHOD":"pp",
         "SELL_ENABLED":true,
         "TRADING_LIMIT":0.002,
	 "TL_PERC": 0,
 	 "TL_ALLIN": false,
         "KEEP_QUOTE": 0,
         "MIN_VOLUME_TO_BUY":0.001,
         "MIN_VOLUME_TO_SELL":0.001,
         "IGNORE_TRADES_BEFORE":0,
         "TRADING_FEES":0.25,
         "FUNDS_RESERVE":0.0001,
		 
         "HIGH_BB":45,
         "LOW_BB":45,
         "CANDLES_LENGTH":99,
         "PERIOD":15,
         "EMA_LENGTH":50,
         "EMA1":16,
         "EMA2":8,
         "STDV":2,
         "SMAPERIOD":50,
         "SLOW_SMA":2,
         "FAST_SMA":1,
         "MACD_SHORT":12,
         "MACD_LONG":26,
         "MACD_SIGNAL":9,
         "STOCH_ENABLED":false,
         "STOCH_METHOD":"oscillator",
         "STOCH_BUY_LEVEL":20,
         "STOCH_SELL_LEVEL":80,
         "STOCH_K":14,
         "SLOW_STOCH_K":3,
         "STOCH_D":3,
         "DI_PERIOD":14,
         "EMASPREAD":false,
         "EMAx":0.5,
         "ADX_LEVEL":25,
         "ADX_ENABLED":false,
         "RSI_BUY_ENABLED":false,
         "RSI_SELL_ENABLED":false,
         "RSI_METHOD":"oscillator",
         "RSI_BUY_LEVEL":30,
         "RSI_SELL_LEVEL":70,
         "RSI_LENGTH":14,
         "MFI_ENABLED":false,
         "MFI_LENGTH":14,
         "MFI_SELL_LEVEL":30,
         "MFI_BUY_LEVEL":70,
         "KUMO_SENTIMENTS":true,
         "ATRX":3,
         "ATR_PERIOD":14,
         "BTC_PND_PROTECTION":false,
         "BTC_MONEY_FLOW":35,
		 
         "DOUBLE_UP":false,
         "DOUBLE_UP_CAP":1,
         "DU_CAP_COUNT":0,
         "DU_METHOD":"HIGHBB",
         "DU_BUYDOWN":2,
         "RSI_DU_BUY":30,
		 
         "RT_ENABLED":true,
         "RT_MAXBAG_PROTECTION":10,
         "RT_SELL_UP":0.1,
         "RT_TREND_ENABLED":true,
         "RT_BUY_LEVEL":0.8,
         "RT_BUYLVL1":0.6,
         "RT_BUYLVL2":2,
         "RT_BUYLVL3":70,
         "RT_BUYLVL":1,
         "RT_GAIN":0.1,
         "RT_SELLLVL1":0.6,
         "RT_SELLLVL2":2,
         "RT_SELLLVL3":70,
         "RT_SELLLVL":1,
		 
         "TRAIL_ME_BUY":false,
         "TRAIL_ME_SELL":false,
         "TRAIL_ME_DU":false,
         "TM_RT_SELL":false,
         "TRAIL_ME_RT":false,
         "TRAIL_ME_SELL_RANGE":0.5,
         "TRAIL_ME_BUY_RANGE":0.5,
         "TRAIL_ME_RT_SELL_RANGE":0.5,
		 
         "PANIC_SELL":false,
         "STOP_LIMIT":60,
         "TRADES_TIMEOUT":0,
		 
         "BUY_LEVEL":1,
         "GAIN":0.1,
		 
         "BUYLVL1":0.6,
         "BUYLVL2":2,
         "BUYLVL3":70,
         "BUYLVL":1,
         "SELLLVL1":0.6,
         "SELLLVL2":2,
         "SELLLVL3":70,
         "SELLLVL":1,
		 
         "BUY_RANGE":0.1,
         "SELL_RANGE":0.1,
         "TSSL_TARGET_ONLY":true,
		 
		 "TAKE_PROFIT": false,
		 "TP_RANGE": 0.5
      },
      "tsa":{
         "BUY_METHOD":"tsa",
         "BUY_ENABLED":true,
         "SELL_METHOD":"tsa",
         "SELL_ENABLED":true,
         "TRADING_LIMIT":0.002,
	 "TL_PERC": 0,
 	 "TL_ALLIN": false,
         "KEEP_QUOTE": 0,
         "MIN_VOLUME_TO_BUY":0.001,
         "MIN_VOLUME_TO_SELL":0.001,
         "IGNORE_TRADES_BEFORE":0,
         "TRADING_FEES":0.25,
         "FUNDS_RESERVE":0.0001,
		 
         "HIGH_BB":45,
         "LOW_BB":45,
         "CANDLES_LENGTH":99,
         "PERIOD":15,
         "EMA_LENGTH":50,
         "EMA1":16,
         "EMA2":8,
         "STDV":2,
         "SMAPERIOD":50,
         "SLOW_SMA":2,
         "FAST_SMA":1,
         "MACD_SHORT":12,
         "MACD_LONG":26,
         "MACD_SIGNAL":9,
         "STOCH_ENABLED":false,
         "STOCH_METHOD":"oscillator",
         "STOCH_BUY_LEVEL":20,
         "STOCH_SELL_LEVEL":80,
         "STOCH_K":14,
         "SLOW_STOCH_K":3,
         "STOCH_D":3,
         "DI_PERIOD":14,
         "EMASPREAD":false,
         "EMAx":0.5,
         "ADX_LEVEL":25,
         "ADX_ENABLED":false,
         "RSI_BUY_ENABLED":false,
         "RSI_SELL_ENABLED":false,
         "RSI_METHOD":"oscillator",
         "RSI_BUY_LEVEL":30,
         "RSI_SELL_LEVEL":70,
         "RSI_LENGTH":14,
         "MFI_ENABLED":false,
         "MFI_LENGTH":14,
         "MFI_SELL_LEVEL":30,
         "MFI_BUY_LEVEL":70,
         "KUMO_SENTIMENTS":true,
         "ATRX":3,
         "ATR_PERIOD":14,
         "BTC_PND_PROTECTION":false,
         "BTC_MONEY_FLOW":35,
		 
         "DOUBLE_UP":false,
         "DOUBLE_UP_CAP":1,
         "DU_CAP_COUNT":0,
         "DU_METHOD":"HIGHBB",
         "DU_BUYDOWN":2,
         "RSI_DU_BUY":30,
		 
         "RT_ENABLED":true,
         "RT_MAXBAG_PROTECTION":10,
         "RT_SELL_UP":0.1,
         "RT_TREND_ENABLED":true,
         "RT_BUY_LEVEL":0.8,
         "RT_BUYLVL1":0.6,
         "RT_BUYLVL2":2,
         "RT_BUYLVL3":70,
         "RT_BUYLVL":1,
         "RT_GAIN":0.1,
         "RT_SELLLVL1":0.6,
         "RT_SELLLVL2":2,
         "RT_SELLLVL3":70,
         "RT_SELLLVL":1,
		 
         "TRAIL_ME_BUY":false,
         "TRAIL_ME_SELL":false,
         "TRAIL_ME_DU":false,
         "TM_RT_SELL":false,
         "TRAIL_ME_RT":false,
         "TRAIL_ME_SELL_RANGE":0.5,
         "TRAIL_ME_BUY_RANGE":0.5,
         "TRAIL_ME_RT_SELL_RANGE":0.5,
		 
         "PANIC_SELL":false,
         "STOP_LIMIT":60,
         "TRADES_TIMEOUT":0,
		 
         "BUY_LEVEL":1,
         "GAIN":0.1,
		 
         "BUYLVL1":0.6,
         "BUYLVL2":2,
         "BUYLVL3":70,
         "BUYLVL":1,
         "SELLLVL1":0.6,
         "SELLLVL2":2,
         "SELLLVL3":70,
         "SELLLVL":1,
		 
         "BUY_RANGE":0.1,
         "SELL_RANGE":0.1,
         "TSSL_TARGET_ONLY":true,
		 
		 "TAKE_PROFIT": false,
		 "TP_RANGE": 0.5,
		 
         "PP_BUY":0,
         "PP_SELL":99999
      },
      "BBTA":{
         "BUY_LEVEL":0.1,
         "GAIN":0.1,
         "HIGH_BB":45,
         "LOW_BB":45,
		 
         "BUY_METHOD":"BBTA",
         "BUY_ENABLED":true,
         "SELL_METHOD":"BBTA",
         "SELL_ENABLED":true,
         "TRADING_LIMIT":0.002,
	 "TL_PERC": 0,
 	 "TL_ALLIN": false,
         "KEEP_QUOTE": 0,
         "MIN_VOLUME_TO_BUY":0.001,
         "MIN_VOLUME_TO_SELL":0.001,
         "IGNORE_TRADES_BEFORE":0,
         "TRADING_FEES":0.25,
         "FUNDS_RESERVE":0.0001,
		 
         "CANDLES_LENGTH":99,
         "PERIOD":15,
         "EMA_LENGTH":50,
         "EMA1":16,
         "EMA2":8,
         "STDV":2,
         "SMAPERIOD":50,
         "SLOW_SMA":2,
         "FAST_SMA":1,
         "MACD_SHORT":12,
         "MACD_LONG":26,
         "MACD_SIGNAL":9,
         "STOCH_ENABLED":false,
         "STOCH_METHOD":"oscillator",
         "STOCH_BUY_LEVEL":20,
         "STOCH_SELL_LEVEL":80,
         "STOCH_K":14,
         "SLOW_STOCH_K":3,
         "STOCH_D":3,
         "DI_PERIOD":14,
         "EMASPREAD":false,
         "EMAx":0.5,
         "ADX_LEVEL":25,
         "ADX_ENABLED":false,
         "RSI_BUY_ENABLED":false,
         "RSI_SELL_ENABLED":false,
         "RSI_METHOD":"oscillator",
         "RSI_BUY_LEVEL":30,
         "RSI_SELL_LEVEL":70,
         "RSI_LENGTH":14,
         "MFI_ENABLED":false,
         "MFI_LENGTH":14,
         "MFI_SELL_LEVEL":30,
         "MFI_BUY_LEVEL":70,
         "KUMO_SENTIMENTS":true,
         "ATRX":3,
         "ATR_PERIOD":14,
         "BTC_PND_PROTECTION":false,
         "BTC_MONEY_FLOW":35,
		 
         "DOUBLE_UP":false,
         "DOUBLE_UP_CAP":1,
         "DU_CAP_COUNT":0,
         "DU_METHOD":"HIGHBB",
         "DU_BUYDOWN":2,
         "RSI_DU_BUY":30,
		 
         "RT_ENABLED":true,
         "RT_MAXBAG_PROTECTION":10,
         "RT_SELL_UP":0.1,
         "RT_TREND_ENABLED":true,
         "RT_BUY_LEVEL":0.8,
         "RT_BUYLVL1":0.6,
         "RT_BUYLVL2":2,
         "RT_BUYLVL3":70,
         "RT_BUYLVL":1,
         "RT_GAIN":0.1,
         "RT_SELLLVL1":0.6,
         "RT_SELLLVL2":2,
         "RT_SELLLVL3":70,
         "RT_SELLLVL":1,
		 
         "TRAIL_ME_BUY":false,
         "TRAIL_ME_SELL":false,
         "TRAIL_ME_DU":false,
         "TM_RT_SELL":false,
         "TRAIL_ME_RT":false,
         "TRAIL_ME_SELL_RANGE":0.5,
         "TRAIL_ME_BUY_RANGE":0.5,
         "TRAIL_ME_RT_SELL_RANGE":0.5,
		 
         "PANIC_SELL":false,
         "STOP_LIMIT":60,
         "TRADES_TIMEOUT":0,
		 
         "BUYLVL1":0.6,
         "BUYLVL2":2,
         "BUYLVL3":70,
         "BUYLVL":1,
         "SELLLVL1":0.6,
         "SELLLVL2":2,
         "SELLLVL3":70,
         "SELLLVL":1,
		 
         "BUY_RANGE":0.1,
         "SELL_RANGE":0.1,
		 "TSSL_TARGET_ONLY":true,
		 
		 "TAKE_PROFIT": false,
		 "TP_RANGE": 0.5,
		 
         "PP_BUY":0,
         "PP_SELL":99999
      },
      "SMACROSS":{
         "SLOW_SMA":2,
         "FAST_SMA":1,
		 
         "BUY_METHOD":"SMACROSS",
         "BUY_ENABLED":true,
         "SELL_METHOD":"SMACROSS",
         "SELL_ENABLED":true,
         "TRADING_LIMIT":0.002,
	 "TL_PERC": 0,
 	 "TL_ALLIN": false,
         "KEEP_QUOTE": 0,
         "MIN_VOLUME_TO_BUY":0.001,
         "MIN_VOLUME_TO_SELL":0.001,
         "IGNORE_TRADES_BEFORE":0,
         "TRADING_FEES":0.25,
         "FUNDS_RESERVE":0.0001,
		 
         "HIGH_BB":45,
         "LOW_BB":45,
         "CANDLES_LENGTH":99,
         "PERIOD":15,
         "EMA_LENGTH":50,
         "EMA1":16,
         "EMA2":8,
         "STDV":2,
         "SMAPERIOD":50,
         "MACD_SHORT":12,
         "MACD_LONG":26,
         "MACD_SIGNAL":9,
         "STOCH_ENABLED":false,
         "STOCH_METHOD":"oscillator",
         "STOCH_BUY_LEVEL":20,
         "STOCH_SELL_LEVEL":80,
         "STOCH_K":14,
         "SLOW_STOCH_K":3,
         "STOCH_D":3,
         "DI_PERIOD":14,
         "EMASPREAD":false,
         "EMAx":0.5,
         "ADX_LEVEL":25,
         "ADX_ENABLED":false,
         "RSI_BUY_ENABLED":false,
         "RSI_SELL_ENABLED":false,
         "RSI_METHOD":"oscillator",
         "RSI_BUY_LEVEL":30,
         "RSI_SELL_LEVEL":70,
         "RSI_LENGTH":14,
         "MFI_ENABLED":false,
         "MFI_LENGTH":14,
         "MFI_SELL_LEVEL":30,
         "MFI_BUY_LEVEL":70,
         "KUMO_SENTIMENTS":true,
         "ATRX":3,
         "ATR_PERIOD":14,
         "BTC_PND_PROTECTION":false,
         "BTC_MONEY_FLOW":35,
		 
         "DOUBLE_UP":false,
         "DOUBLE_UP_CAP":1,
         "DU_CAP_COUNT":0,
         "DU_METHOD":"HIGHBB",
         "DU_BUYDOWN":2,
         "RSI_DU_BUY":30,
		 
         "RT_ENABLED":true,
         "RT_MAXBAG_PROTECTION":10,
         "RT_SELL_UP":0.1,
         "RT_TREND_ENABLED":true,
         "RT_BUY_LEVEL":0.8,
         "RT_BUYLVL1":0.6,
         "RT_BUYLVL2":2,
         "RT_BUYLVL3":70,
         "RT_BUYLVL":1,
         "RT_GAIN":0.1,
         "RT_SELLLVL1":0.6,
         "RT_SELLLVL2":2,
         "RT_SELLLVL3":70,
         "RT_SELLLVL":1,
		 
         "TRAIL_ME_BUY":false,
         "TRAIL_ME_SELL":false,
         "TRAIL_ME_DU":false,
         "TM_RT_SELL":false,
         "TRAIL_ME_RT":false,
         "TRAIL_ME_SELL_RANGE":0.5,
         "TRAIL_ME_BUY_RANGE":0.5,
         "TRAIL_ME_RT_SELL_RANGE":0.5,
		 
         "PANIC_SELL":false,
         "STOP_LIMIT":60,
         "TRADES_TIMEOUT":0,
		 
         "BUY_LEVEL":1,
         "GAIN":0.1,
		 
         "BUYLVL1":0.6,
         "BUYLVL2":2,
         "BUYLVL3":70,
         "BUYLVL":1,
         "SELLLVL1":0.6,
         "SELLLVL2":2,
         "SELLLVL3":70,
         "SELLLVL":1,
		 
         "BUY_RANGE":0.1,
         "SELL_RANGE":0.1,
         "TSSL_TARGET_ONLY":true,
		 
		 "TAKE_PROFIT": false,
		 "TP_RANGE": 0.5,
		 
         "PP_BUY":0,
         "PP_SELL":99999
      },
      "MACD":{
         "MACD_SHORT":12,
         "MACD_LONG":26,
         "MACD_SIGNAL":9,
		 
         "BUY_METHOD":"MACD",
         "BUY_ENABLED":true,
         "SELL_METHOD":"MACD",
         "SELL_ENABLED":true,
         "TRADING_LIMIT":0.002,
	 "TL_PERC": 0,
 	 "TL_ALLIN": false,
         "KEEP_QUOTE": 0,
         "MIN_VOLUME_TO_BUY":0.001,
         "MIN_VOLUME_TO_SELL":0.001,
         "IGNORE_TRADES_BEFORE":0,
         "TRADING_FEES":0.25,
         "FUNDS_RESERVE":0.0001,
		 
         "HIGH_BB":45,
         "LOW_BB":45,
         "CANDLES_LENGTH":99,
         "PERIOD":15,
         "EMA_LENGTH":50,
         "EMA1":16,
         "EMA2":8,
         "STDV":2,
         "SMAPERIOD":50,
         "SLOW_SMA":2,
         "FAST_SMA":1,
         "STOCH_ENABLED":false,
         "STOCH_METHOD":"oscillator",
         "STOCH_BUY_LEVEL":20,
         "STOCH_SELL_LEVEL":80,
         "STOCH_K":14,
         "SLOW_STOCH_K":3,
         "STOCH_D":3,
         "DI_PERIOD":14,
         "EMASPREAD":false,
         "EMAx":0.5,
         "ADX_LEVEL":25,
         "ADX_ENABLED":false,
         "RSI_BUY_ENABLED":false,
         "RSI_SELL_ENABLED":false,
         "RSI_METHOD":"oscillator",
         "RSI_BUY_LEVEL":30,
         "RSI_SELL_LEVEL":70,
         "RSI_LENGTH":14,
         "MFI_ENABLED":false,
         "MFI_LENGTH":14,
         "MFI_SELL_LEVEL":30,
         "MFI_BUY_LEVEL":70,
         "KUMO_SENTIMENTS":true,
         "ATRX":3,
         "ATR_PERIOD":14,
         "BTC_PND_PROTECTION":false,
         "BTC_MONEY_FLOW":35,
		 
         "DOUBLE_UP":false,
         "DOUBLE_UP_CAP":1,
         "DU_CAP_COUNT":0,
         "DU_METHOD":"HIGHBB",
         "DU_BUYDOWN":2,
         "RSI_DU_BUY":30,
		 
         "RT_ENABLED":true,
         "RT_MAXBAG_PROTECTION":10,
         "RT_SELL_UP":0.1,
         "RT_TREND_ENABLED":true,
         "RT_BUY_LEVEL":0.8,
         "RT_BUYLVL1":0.6,
         "RT_BUYLVL2":2,
         "RT_BUYLVL3":70,
         "RT_BUYLVL":1,
         "RT_GAIN":0.1,
         "RT_SELLLVL1":0.6,
         "RT_SELLLVL2":2,
         "RT_SELLLVL3":70,
         "RT_SELLLVL":1,
		 
         "TRAIL_ME_BUY":false,
         "TRAIL_ME_SELL":false,
         "TRAIL_ME_DU":false,
         "TM_RT_SELL":false,
         "TRAIL_ME_RT":false,
         "TRAIL_ME_SELL_RANGE":0.5,
         "TRAIL_ME_BUY_RANGE":0.5,
         "TRAIL_ME_RT_SELL_RANGE":0.5,
		 
         "PANIC_SELL":false,
         "STOP_LIMIT":60,
         "TRADES_TIMEOUT":0,
		 
         "BUY_LEVEL":1,
         "GAIN":0.1,
		 
         "BUYLVL1":0.6,
         "BUYLVL2":2,
         "BUYLVL3":70,
         "BUYLVL":1,
         "SELLLVL1":0.6,
         "SELLLVL2":2,
         "SELLLVL3":70,
         "SELLLVL":1,
		 
         "BUY_RANGE":0.1,
         "SELL_RANGE":0.1,
         "TSSL_TARGET_ONLY":true,
		 
		 "TAKE_PROFIT": false,
		 "TP_RANGE": 0.5,
		 
         "PP_BUY":0,
         "PP_SELL":99999
      },
      "MACDH":{
         "MACD_SHORT":12,
         "MACD_LONG":26,
         "MACD_SIGNAL":9,
		 
         "BUY_METHOD":"MACDH",
         "BUY_ENABLED":true,
         "SELL_METHOD":"MACDH",
         "SELL_ENABLED":true,
         "TRADING_LIMIT":0.002,
	 "TL_PERC": 0,
 	 "TL_ALLIN": false,
         "KEEP_QUOTE": 0,
         "MIN_VOLUME_TO_BUY":0.001,
         "MIN_VOLUME_TO_SELL":0.001,
         "IGNORE_TRADES_BEFORE":0,
         "TRADING_FEES":0.25,
         "FUNDS_RESERVE":0.0001,
		 
         "HIGH_BB":45,
         "LOW_BB":45,
         "CANDLES_LENGTH":99,
         "PERIOD":15,
         "EMA_LENGTH":50,
         "EMA1":16,
         "EMA2":8,
         "STDV":2,
         "SMAPERIOD":50,
         "SLOW_SMA":2,
         "FAST_SMA":1,
         "STOCH_ENABLED":false,
         "STOCH_METHOD":"oscillator",
         "STOCH_BUY_LEVEL":20,
         "STOCH_SELL_LEVEL":80,
         "STOCH_K":14,
         "SLOW_STOCH_K":3,
         "STOCH_D":3,
         "DI_PERIOD":14,
         "EMASPREAD":false,
         "EMAx":0.5,
         "ADX_LEVEL":25,
         "ADX_ENABLED":false,
         "RSI_BUY_ENABLED":false,
         "RSI_SELL_ENABLED":false,
         "RSI_METHOD":"oscillator",
         "RSI_BUY_LEVEL":30,
         "RSI_SELL_LEVEL":70,
         "RSI_LENGTH":14,
         "MFI_ENABLED":false,
         "MFI_LENGTH":14,
         "MFI_SELL_LEVEL":30,
         "MFI_BUY_LEVEL":70,
         "KUMO_SENTIMENTS":true,
         "ATRX":3,
         "ATR_PERIOD":14,
         "BTC_PND_PROTECTION":false,
         "BTC_MONEY_FLOW":35,
		 
         "DOUBLE_UP":false,
         "DOUBLE_UP_CAP":1,
         "DU_CAP_COUNT":0,
         "DU_METHOD":"HIGHBB",
         "DU_BUYDOWN":2,
         "RSI_DU_BUY":30,
		 
         "RT_ENABLED":true,
         "RT_MAXBAG_PROTECTION":10,
         "RT_SELL_UP":0.1,
         "RT_TREND_ENABLED":true,
         "RT_BUY_LEVEL":0.8,
         "RT_BUYLVL1":0.6,
         "RT_BUYLVL2":2,
         "RT_BUYLVL3":70,
         "RT_BUYLVL":1,
         "RT_GAIN":0.1,
         "RT_SELLLVL1":0.6,
         "RT_SELLLVL2":2,
         "RT_SELLLVL3":70,
         "RT_SELLLVL":1,
		 
         "TRAIL_ME_BUY":false,
         "TRAIL_ME_SELL":false,
         "TRAIL_ME_DU":false,
         "TM_RT_SELL":false,
         "TRAIL_ME_RT":false,
         "TRAIL_ME_SELL_RANGE":0.5,
         "TRAIL_ME_BUY_RANGE":0.5,
         "TRAIL_ME_RT_SELL_RANGE":0.5,
		 
         "PANIC_SELL":false,
         "STOP_LIMIT":60,
         "TRADES_TIMEOUT":0,
		 
         "BUY_LEVEL":1,
         "GAIN":0.1,
		 
         "BUYLVL1":0.6,
         "BUYLVL2":2,
         "BUYLVL3":70,
         "BUYLVL":1,
         "SELLLVL1":0.6,
         "SELLLVL2":2,
         "SELLLVL3":70,
         "SELLLVL":1,
		 
         "BUY_RANGE":0.1,
         "SELL_RANGE":0.1,
         "TSSL_TARGET_ONLY":true,
		 
		 "TAKE_PROFIT": false,
		 "TP_RANGE": 0.5,
		 
         "PP_BUY":0,
         "PP_SELL":99999
      },
      "ADX":{
         "ADX_LEVEL":25,
		 
         "BUY_METHOD":"ADX",
         "BUY_ENABLED":true,
         "SELL_METHOD":"ADX",
         "SELL_ENABLED":true,
         "TRADING_LIMIT":0.002,
	 "TL_PERC": 0,
 	 "TL_ALLIN": false,
         "KEEP_QUOTE": 0,
         "MIN_VOLUME_TO_BUY":0.001,
         "MIN_VOLUME_TO_SELL":0.001,
         "IGNORE_TRADES_BEFORE":0,
         "TRADING_FEES":0.25,
         "FUNDS_RESERVE":0.0001,
		 
         "HIGH_BB":45,
         "LOW_BB":45,
         "CANDLES_LENGTH":99,
         "PERIOD":15,
         "EMA_LENGTH":50,
         "EMA1":16,
         "EMA2":8,
         "STDV":2,
         "SMAPERIOD":50,
         "SLOW_SMA":2,
         "FAST_SMA":1,
         "MACD_SHORT":12,
         "MACD_LONG":26,
         "MACD_SIGNAL":9,
         "STOCH_ENABLED":false,
         "STOCH_METHOD":"oscillator",
         "STOCH_BUY_LEVEL":20,
         "STOCH_SELL_LEVEL":80,
         "STOCH_K":14,
         "SLOW_STOCH_K":3,
         "STOCH_D":3,
         "DI_PERIOD":14,
         "EMASPREAD":false,
         "EMAx":0.5,
         "ADX_ENABLED":false,
         "RSI_BUY_ENABLED":false,
         "RSI_SELL_ENABLED":false,
         "RSI_METHOD":"oscillator",
         "RSI_BUY_LEVEL":30,
         "RSI_SELL_LEVEL":70,
         "RSI_LENGTH":14,
         "MFI_ENABLED":false,
         "MFI_LENGTH":14,
         "MFI_SELL_LEVEL":30,
         "MFI_BUY_LEVEL":70,
         "KUMO_SENTIMENTS":true,
         "ATRX":3,
         "ATR_PERIOD":14,
         "BTC_PND_PROTECTION":false,
         "BTC_MONEY_FLOW":35,
		 
         "DOUBLE_UP":false,
         "DOUBLE_UP_CAP":1,
         "DU_CAP_COUNT":0,
         "DU_METHOD":"HIGHBB",
         "DU_BUYDOWN":2,
         "RSI_DU_BUY":30,
		 
         "RT_ENABLED":true,
         "RT_MAXBAG_PROTECTION":10,
         "RT_SELL_UP":0.1,
         "RT_TREND_ENABLED":true,
         "RT_BUY_LEVEL":0.8,
         "RT_BUYLVL1":0.6,
         "RT_BUYLVL2":2,
         "RT_BUYLVL3":70,
         "RT_BUYLVL":1,
         "RT_GAIN":0.1,
         "RT_SELLLVL1":0.6,
         "RT_SELLLVL2":2,
         "RT_SELLLVL3":70,
         "RT_SELLLVL":1,
		 
         "TRAIL_ME_BUY":false,
         "TRAIL_ME_SELL":false,
         "TRAIL_ME_DU":false,
         "TM_RT_SELL":false,
         "TRAIL_ME_RT":false,
         "TRAIL_ME_SELL_RANGE":0.5,
         "TRAIL_ME_BUY_RANGE":0.5,
         "TRAIL_ME_RT_SELL_RANGE":0.5,
		 
         "PANIC_SELL":false,
         "STOP_LIMIT":60,
         "TRADES_TIMEOUT":0,
		 
         "BUY_LEVEL":1,
         "GAIN":0.1,
		 
         "BUYLVL1":0.6,
         "BUYLVL2":2,
         "BUYLVL3":70,
         "BUYLVL":1,
         "SELLLVL1":0.6,
         "SELLLVL2":2,
         "SELLLVL3":70,
         "SELLLVL":1,
		 
         "BUY_RANGE":0.1,
         "SELL_RANGE":0.1,
         "TSSL_TARGET_ONLY":true,
		 
		 "TAKE_PROFIT": false,
		 "TP_RANGE": 0.5,
		 
         "PP_BUY":0,
         "PP_SELL":99999
      },
      "EMASPREAD":{
         "EMAx":0.5,
		 
         "BUY_METHOD":"EMASPREAD",
         "BUY_ENABLED":true,
         "SELL_METHOD":"EMASPREAD",
         "SELL_ENABLED":true,
         "TRADING_LIMIT":0.002,
	 "TL_PERC": 0,
 	 "TL_ALLIN": false,
         "KEEP_QUOTE": 0,
         "MIN_VOLUME_TO_BUY":0.001,
         "MIN_VOLUME_TO_SELL":0.001,
         "IGNORE_TRADES_BEFORE":0,
         "TRADING_FEES":0.25,
         "FUNDS_RESERVE":0.0001,
		 
         "HIGH_BB":45,
         "LOW_BB":45,
         "CANDLES_LENGTH":99,
         "PERIOD":15,
         "EMA_LENGTH":50,
         "EMA1":16,
         "EMA2":8,
         "STDV":2,
         "SMAPERIOD":50,
         "SLOW_SMA":2,
         "FAST_SMA":1,
         "MACD_SHORT":12,
         "MACD_LONG":26,
         "MACD_SIGNAL":9,
         "STOCH_ENABLED":false,
         "STOCH_METHOD":"oscillator",
         "STOCH_BUY_LEVEL":20,
         "STOCH_SELL_LEVEL":80,
         "STOCH_K":14,
         "SLOW_STOCH_K":3,
         "STOCH_D":3,
         "DI_PERIOD":14,
         "EMASPREAD":false,
         "ADX_LEVEL":25,
         "ADX_ENABLED":false,
         "RSI_BUY_ENABLED":false,
         "RSI_SELL_ENABLED":false,
         "RSI_METHOD":"oscillator",
         "RSI_BUY_LEVEL":30,
         "RSI_SELL_LEVEL":70,
         "RSI_LENGTH":14,
         "MFI_ENABLED":false,
         "MFI_LENGTH":14,
         "MFI_SELL_LEVEL":30,
         "MFI_BUY_LEVEL":70,
         "KUMO_SENTIMENTS":true,
         "ATRX":3,
         "ATR_PERIOD":14,
         "BTC_PND_PROTECTION":false,
         "BTC_MONEY_FLOW":35,
		 
         "DOUBLE_UP":false,
         "DOUBLE_UP_CAP":1,
         "DU_CAP_COUNT":0,
         "DU_METHOD":"HIGHBB",
         "DU_BUYDOWN":2,
         "RSI_DU_BUY":30,
		 
         "RT_ENABLED":true,
         "RT_MAXBAG_PROTECTION":10,
         "RT_SELL_UP":0.1,
         "RT_TREND_ENABLED":true,
         "RT_BUY_LEVEL":0.8,
         "RT_BUYLVL1":0.6,
         "RT_BUYLVL2":2,
         "RT_BUYLVL3":70,
         "RT_BUYLVL":1,
         "RT_GAIN":0.1,
         "RT_SELLLVL1":0.6,
         "RT_SELLLVL2":2,
         "RT_SELLLVL3":70,
         "RT_SELLLVL":1,
		 
         "TRAIL_ME_BUY":false,
         "TRAIL_ME_SELL":false,
         "TRAIL_ME_DU":false,
         "TM_RT_SELL":false,
         "TRAIL_ME_RT":false,
         "TRAIL_ME_SELL_RANGE":0.5,
         "TRAIL_ME_BUY_RANGE":0.5,
         "TRAIL_ME_RT_SELL_RANGE":0.5,
		 
         "PANIC_SELL":false,
         "STOP_LIMIT":60,
         "TRADES_TIMEOUT":0,
		 
         "BUYLVL1":0.6,
         "BUYLVL2":2,
         "BUYLVL3":70,
         "BUYLVL":1,
         "SELLLVL1":0.6,
         "SELLLVL2":2,
         "SELLLVL3":70,
         "SELLLVL":1,
		 
		 "BUY_LEVEL":0.1,
         "GAIN":0.1,
		 
         "BUY_RANGE":0.1,
         "SELL_RANGE":0.1,
         "TSSL_TARGET_ONLY":true,
		 
		 "TAKE_PROFIT": false,
		 "TP_RANGE": 0.5,
		 
         "PP_BUY":0,
         "PP_SELL":99999
      },
      "emotionless":{
         "BUY_LEVEL":0.1,
         "GAIN":0.1,
		 
         "BUY_METHOD":"emotionless",
         "BUY_ENABLED":true,
         "SELL_METHOD":"emotionless",
         "SELL_ENABLED":true,
         "TRADING_LIMIT":0.002,
	 "TL_PERC": 0,
 	 "TL_ALLIN": false,
         "KEEP_QUOTE": 0,
         "MIN_VOLUME_TO_BUY":0.001,
         "MIN_VOLUME_TO_SELL":0.001,
         "IGNORE_TRADES_BEFORE":0,
         "TRADING_FEES":0.25,
         "FUNDS_RESERVE":0.0001,
		 
         "HIGH_BB":45,
         "LOW_BB":45,
         "CANDLES_LENGTH":99,
         "PERIOD":15,
         "EMA_LENGTH":50,
         "EMA1":16,
         "EMA2":8,
         "STDV":2,
         "SMAPERIOD":50,
         "SLOW_SMA":2,
         "FAST_SMA":1,
         "MACD_SHORT":12,
         "MACD_LONG":26,
         "MACD_SIGNAL":9,
         "STOCH_ENABLED":false,
         "STOCH_METHOD":"oscillator",
         "STOCH_BUY_LEVEL":20,
         "STOCH_SELL_LEVEL":80,
         "STOCH_K":14,
         "SLOW_STOCH_K":3,
         "STOCH_D":3,
         "DI_PERIOD":14,
         "EMASPREAD":false,
         "EMAx":0.5,
         "ADX_LEVEL":25,
         "ADX_ENABLED":false,
         "RSI_BUY_ENABLED":false,
         "RSI_SELL_ENABLED":false,
         "RSI_METHOD":"oscillator",
         "RSI_BUY_LEVEL":30,
         "RSI_SELL_LEVEL":70,
         "RSI_LENGTH":14,
         "MFI_ENABLED":false,
         "MFI_LENGTH":14,
         "MFI_SELL_LEVEL":30,
         "MFI_BUY_LEVEL":70,
         "KUMO_SENTIMENTS":true,
         "ATRX":3,
         "ATR_PERIOD":14,
         "BTC_PND_PROTECTION":false,
         "BTC_MONEY_FLOW":35,
		 
         "DOUBLE_UP":false,
         "DOUBLE_UP_CAP":1,
         "DU_CAP_COUNT":0,
         "DU_METHOD":"HIGHBB",
         "DU_BUYDOWN":2,
         "RSI_DU_BUY":30,
		 
         "RT_ENABLED":true,
         "RT_MAXBAG_PROTECTION":10,
         "RT_SELL_UP":0.1,
         "RT_TREND_ENABLED":true,
         "RT_BUY_LEVEL":0.8,
         "RT_BUYLVL1":0.6,
         "RT_BUYLVL2":2,
         "RT_BUYLVL3":70,
         "RT_BUYLVL":1,
         "RT_GAIN":0.1,
         "RT_SELLLVL1":0.6,
         "RT_SELLLVL2":2,
         "RT_SELLLVL3":70,
         "RT_SELLLVL":1,
		 
         "TRAIL_ME_BUY":false,
         "TRAIL_ME_SELL":false,
         "TRAIL_ME_DU":false,
         "TM_RT_SELL":false,
         "TRAIL_ME_RT":false,
         "TRAIL_ME_SELL_RANGE":0.5,
         "TRAIL_ME_BUY_RANGE":0.5,
         "TRAIL_ME_RT_SELL_RANGE":0.5,
		 
         "PANIC_SELL":false,
         "STOP_LIMIT":60,
         "TRADES_TIMEOUT":0,
		 
         "BUYLVL1":0.6,
         "BUYLVL2":2,
         "BUYLVL3":70,
         "BUYLVL":1,
         "SELLLVL1":0.6,
         "SELLLVL2":2,
         "SELLLVL3":70,
         "SELLLVL":1,
		 
         "BUY_RANGE":0.1,
         "SELL_RANGE":0.1,
         "TSSL_TARGET_ONLY":true,
		 
		 "TAKE_PROFIT": false,
		 "TP_RANGE": 0.5,
		 
         "PP_BUY":0,
         "PP_SELL":99999
      },
      "ATRTS":{
         "ATRX":3,

         "BUY_METHOD":"ATRTS",
         "BUY_ENABLED":true,
         "SELL_METHOD":"ATRTS",
         "SELL_ENABLED":true,
         "TRADING_LIMIT":0.002,
	 "TL_PERC": 0,
 	 "TL_ALLIN": false,
         "KEEP_QUOTE": 0,
         "MIN_VOLUME_TO_BUY":0.001,
         "MIN_VOLUME_TO_SELL":0.001,
         "IGNORE_TRADES_BEFORE":0,
         "TRADING_FEES":0.25,
         "FUNDS_RESERVE":0.0001,
		 
         "HIGH_BB":45,
         "LOW_BB":45,
         "CANDLES_LENGTH":99,
         "PERIOD":15,
         "EMA_LENGTH":50,
         "EMA1":16,
         "EMA2":8,
         "STDV":2,
         "SMAPERIOD":50,
         "SLOW_SMA":2,
         "FAST_SMA":1,
         "MACD_SHORT":12,
         "MACD_LONG":26,
         "MACD_SIGNAL":9,
         "STOCH_ENABLED":false,
         "STOCH_METHOD":"oscillator",
         "STOCH_BUY_LEVEL":20,
         "STOCH_SELL_LEVEL":80,
         "STOCH_K":14,
         "SLOW_STOCH_K":3,
         "STOCH_D":3,
         "DI_PERIOD":14,
         "EMASPREAD":false,
         "EMAx":0.5,
         "ADX_LEVEL":25,
         "ADX_ENABLED":false,
         "RSI_BUY_ENABLED":false,
         "RSI_SELL_ENABLED":false,
         "RSI_METHOD":"oscillator",
         "RSI_BUY_LEVEL":30,
         "RSI_SELL_LEVEL":70,
         "RSI_LENGTH":14,
         "MFI_ENABLED":false,
         "MFI_LENGTH":14,
         "MFI_SELL_LEVEL":30,
         "MFI_BUY_LEVEL":70,
         "KUMO_SENTIMENTS":true,
         "ATR_PERIOD":14,
         "BTC_PND_PROTECTION":false,
         "BTC_MONEY_FLOW":35,
		 
         "DOUBLE_UP":false,
         "DOUBLE_UP_CAP":1,
         "DU_CAP_COUNT":0,
         "DU_METHOD":"HIGHBB",
         "DU_BUYDOWN":2,
         "RSI_DU_BUY":30,
		 
         "RT_ENABLED":true,
         "RT_MAXBAG_PROTECTION":10,
         "RT_SELL_UP":0.1,
         "RT_TREND_ENABLED":true,
         "RT_BUY_LEVEL":0.8,
         "RT_BUYLVL1":0.6,
         "RT_BUYLVL2":2,
         "RT_BUYLVL3":70,
         "RT_BUYLVL":1,
         "RT_GAIN":0.1,
         "RT_SELLLVL1":0.6,
         "RT_SELLLVL2":2,
         "RT_SELLLVL3":70,
         "RT_SELLLVL":1,
		 
         "TRAIL_ME_BUY":false,
         "TRAIL_ME_SELL":false,
         "TRAIL_ME_DU":false,
         "TM_RT_SELL":false,
         "TRAIL_ME_RT":false,
         "TRAIL_ME_SELL_RANGE":0.5,
         "TRAIL_ME_BUY_RANGE":0.5,
         "TRAIL_ME_RT_SELL_RANGE":0.5,
		 
         "PANIC_SELL":false,
         "STOP_LIMIT":60,
         "TRADES_TIMEOUT":0,
		 
         "BUYLVL1":0.6,
         "BUYLVL2":2,
         "BUYLVL3":70,
         "BUYLVL":1,
         "SELLLVL1":0.6,
         "SELLLVL2":2,
         "SELLLVL3":70,
         "SELLLVL":1,
         
		 "BUY_LEVEL":0.1,
         "GAIN":0.1,
		 
		 "BUY_RANGE":0.1,
         "SELL_RANGE":0.1,
         "TSSL_TARGET_ONLY":true,
		 
		 "TAKE_PROFIT": false,
		 "TP_RANGE": 0.5,
		 
         "PP_BUY":0,
         "PP_SELL":99999
      },
      "ichimoku":{
         "BUY_METHOD":"ichimoku",
         "BUY_ENABLED":true,
         "SELL_METHOD":"ichimoku",
         "SELL_ENABLED":true,
         "TRADING_LIMIT":0.002,
	 "TL_PERC": 0,
 	 "TL_ALLIN": false,
         "KEEP_QUOTE": 0,
         "MIN_VOLUME_TO_BUY":0.001,
         "MIN_VOLUME_TO_SELL":0.001,
         "IGNORE_TRADES_BEFORE":0,
         "TRADING_FEES":0.25,
         "FUNDS_RESERVE":0.0001,
		 
         "HIGH_BB":45,
         "LOW_BB":45,
         "CANDLES_LENGTH":99,
         "PERIOD":15,
         "EMA_LENGTH":50,
         "EMA1":16,
         "EMA2":8,
         "STDV":2,
         "SMAPERIOD":50,
         "SLOW_SMA":2,
         "FAST_SMA":1,
         "MACD_SHORT":12,
         "MACD_LONG":26,
         "MACD_SIGNAL":9,
         "STOCH_ENABLED":false,
         "STOCH_METHOD":"oscillator",
         "STOCH_BUY_LEVEL":20,
         "STOCH_SELL_LEVEL":80,
         "STOCH_K":14,
         "SLOW_STOCH_K":3,
         "STOCH_D":3,
         "DI_PERIOD":14,
         "EMASPREAD":false,
         "EMAx":0.5,
         "ADX_LEVEL":25,
         "ADX_ENABLED":false,
         "RSI_BUY_ENABLED":false,
         "RSI_SELL_ENABLED":false,
         "RSI_METHOD":"oscillator",
         "RSI_BUY_LEVEL":30,
         "RSI_SELL_LEVEL":70,
         "RSI_LENGTH":14,
         "MFI_ENABLED":false,
         "MFI_LENGTH":14,
         "MFI_SELL_LEVEL":30,
         "MFI_BUY_LEVEL":70,
	 "TENKAN_PERIOD": 9,
         "KIJUN_PERIOD": 26,
         "SENKOUSPAN_PERIOD": 52,
         "KUMO_SENTIMENTS":true,
         "ATRX":3,
         "ATR_PERIOD":14,
         "BTC_PND_PROTECTION":false,
         "BTC_MONEY_FLOW":35,
		 
         "DOUBLE_UP":false,
         "DOUBLE_UP_CAP":1,
         "DU_CAP_COUNT":0,
         "DU_METHOD":"HIGHBB",
         "DU_BUYDOWN":2,
         "RSI_DU_BUY":30,
		 
         "RT_ENABLED":true,
         "RT_MAXBAG_PROTECTION":10,
         "RT_SELL_UP":0.1,
         "RT_TREND_ENABLED":true,
         "RT_BUY_LEVEL":0.8,
         "RT_BUYLVL1":0.6,
         "RT_BUYLVL2":2,
         "RT_BUYLVL3":70,
         "RT_BUYLVL":1,
         "RT_GAIN":0.1,
         "RT_SELLLVL1":0.6,
         "RT_SELLLVL2":2,
         "RT_SELLLVL3":70,
         "RT_SELLLVL":1,
		 
         "TRAIL_ME_BUY":false,
         "TRAIL_ME_SELL":false,
         "TRAIL_ME_DU":false,
         "TM_RT_SELL":false,
         "TRAIL_ME_RT":false,
         "TRAIL_ME_SELL_RANGE":0.5,
         "TRAIL_ME_BUY_RANGE":0.5,
         "TRAIL_ME_RT_SELL_RANGE":0.5,
		 
         "PANIC_SELL":false,
         "STOP_LIMIT":60,
         "TRADES_TIMEOUT":0,
		 
         "BUY_LEVEL":1,
         "GAIN":0.1,
		 
         "BUYLVL1":0.6,
         "BUYLVL2":2,
         "BUYLVL3":70,
         "BUYLVL":1,
         "SELLLVL1":0.6,
         "SELLLVL2":2,
         "SELLLVL3":70,
         "SELLLVL":1,
		 
         "BUY_RANGE":0.1,
         "SELL_RANGE":0.1,
         "TSSL_TARGET_ONLY":true,
		 
		 "TAKE_PROFIT": false,
		 "TP_RANGE": 0.5,
		 
         "PP_BUY":0,
         "PP_SELL":99999
      }
   },
   "exchanges":{
      "bittrex":{
         "masterkey":"",
         "mastersecret":"",
         "key":"",
         "secret":"",
         "delay": 1
      },
      "poloniex":{
         "masterkey":"",
         "mastersecret":"",
         "key":"",
         "secret":"",
         "delay": 1
      },
      "kraken":{
         "masterkey":"",
         "mastersecret":"",
         "key":"",
         "secret":"",
         "delay": 1
      },
      "cryptopia":{
         "masterkey":"",
         "mastersecret":"",
         "key":"",
         "secret":"",
         "delay": 1
      },
      "bitfinex":{
         "masterkey":"",
         "mastersecret":"",
         "key":"",
         "secret":"",
         "delay": 1
      },
      "binance":{
         "masterkey":"",
         "mastersecret":"",
         "key":"",
         "secret":"",
         "delay": 1
      },
      "cex":{
         "masterkey":"",
         "mastersecret":"",
         "key":"",
         "secret":"",
         "clientId":"",
         "delay": 1
      },
      "gdax":{
         "masterkey":"",
         "mastersecret":"",
         "key":"",
         "secret":"",
         "passphrase":"",
         "delay": 1
      },
      "kucoin":{
         "masterkey":"",
         "mastersecret":"",
         "key":"",
         "secret":"",
         "delay": 1
      }
   },
   "bot":{
      "json_output": "./json",
      "debug":false,
      "BEST_CURRENCIES":false,
      "BOT_DELAY":1,
      "BOT_CCLEAN":2,
      "CANCEL_ORDERS_ENABLED":true,
      "CANCEL_ORDERS_CYCLE_CAP":10,
      "RESERVE_PILE_UP":false,
      "interval_ticker_update":25000,
      "period_storage_ticker":2000,
      "timeout_buy":59000,
      "timeout_sell":60000,
      "PYRAMID_BUY":false,
      "TRADING_LIMIT_BUY_PYRAMID":50,
      "TV_GAIN":0.6,
      "TV_TRADING_LIMIT_BUY":50,
      "TV_TRADING_LIMIT_BUY_PYRAMID":50,
      "TV_PYRAMID":false,
      "TV_TRADING_LIMIT_SELL":50,
      "TV_PROTECTION":false,
      "TV_TRADING_LIMIT_CAP":0.0001,
      "TV_STOPLOSS_PERCENTAGE":60,
      "TV_TRADING_LIMIT_ALLIN":false,
      "TV_MVTS":0.0001,
      "TV_GB": false,
      "RETRY_TV_ORDER":false,
      "VERBOSE":true,
      "WATCH_MODE":false,
      "MINIMUM_VOLUME_GOOD_CURRENCY":200,
      "MINIMUM_VARIATION_SUGGEST_TRADE":1,
      "withdraw_address":"YOURBTCADDRESSHERE",
      "withdraw_threshold":0.5,
      "TELEGRAM_ENABLED":false,
      "TG_ORDER_TIMEOUT": 0,
      "TG_TEST":false,
      "TG_PL_ONLY": false,
      "TELEGRAM_NICK":"Gunbot",
      "TOKEN":"YOURTOKEN",
      "chat_id":"123456789"
   },
   "ws": {
        "port": 5001,
        "clientport": 3000,
        "hostname": "127.0.0.1"
    },
    "GUI": {
        "enabled": true,
        "start": false,
        "port": 5000,
        "https": false,
        "key": "localhost.key",
        "cert": "localhost.crt",
        "networktraffic": false,
        "authentication": {
            "login": true,
            "twoFA": false
        },
        "notifications": {
            "trade": true,
            "callback": false,
            "error": true
        }
    },
   "imap_listener":{
      "enabled":false,
      "authorized_froms":"[\"noreply@tradingview.com\"]",
      "user":"YOUREMAIL",
      "password":"YOURPASSWORD",
      "host":"imap.gmail.com",
      "port":993,
      "tls":true,
      "tlsOptions":{
         "rejectUnauthorized":false
      }
   }
}
